manifest:
  remotes:
    - name: slicemk
      url-base: https://github.com/SorairoNM
  projects:
    - name: slicemk-zmk
      remote: slicemk
      revision: v20230228-mouse
      import: app/west.yml
  self:
    path: config
